/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthenticatedAppJogadoresRouteImport } from './routes/_authenticated/app/jogadores'
import { Route as AuthenticatedAppNotificacoesRouteImport } from './routes/_authenticated/app/notificacoes'
import { Route as AuthenticatedAppPartidasRouteImport } from './routes/_authenticated/app/partidas'
import { Route as AuthenticatedAppPrincipalRouteImport } from './routes/_authenticated/app/principal'
import { Route as AuthenticatedAppRankingsRouteImport } from './routes/_authenticated/app/rankings'
import { Route as AuthenticatedAppRodadasRouteImport } from './routes/_authenticated/app/rodadas'
import { Route as AuthenticatedAppSorteioRouteImport } from './routes/_authenticated/app/sorteio'
import { Route as AuthenticatedAppTorneiosRouteImport } from './routes/_authenticated/app/torneios'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app/admin/index'
import { Route as AuthenticatedAppAdminAuditoriaRouteImport } from './routes/_authenticated/app/admin/auditoria'
import { Route as AuthenticatedAppAdminAvisosRouteImport } from './routes/_authenticated/app/admin/avisos'
import { Route as AuthenticatedAppAdminConfiguracoesRouteImport } from './routes/_authenticated/app/admin/configuracoes'
import { Route as AuthenticatedAppAdminRelatoriosRouteImport } from './routes/_authenticated/app/admin/relatorios'
import { Route as AuthenticatedAppAdminRodadasRouteImport } from './routes/_authenticated/app/admin/rodadas'
import { Route as AuthenticatedAppAdminTemporadasRouteImport } from './routes/_authenticated/app/admin/temporadas'
import { Route as AuthenticatedAppJogadoresIdRouteImport } from './routes/_authenticated/app/jogadores.$id'
import { Route as AuthenticatedAppPartidasIdRouteImport } from './routes/_authenticated/app/partidas.$id'
import { Route as AuthenticatedAppRodadasIdRouteImport } from './routes/_authenticated/app/rodadas.$id'
import { Route as AuthenticatedAppTorneiosIdRouteImport } from './routes/_authenticated/app/torneios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppJogadoresRoute =
  AuthenticatedAppJogadoresRouteImport.update({
    id: '/app/jogadores',
    path: '/app/jogadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNotificacoesRoute =
  AuthenticatedAppNotificacoesRouteImport.update({
    id: '/app/notificacoes',
    path: '/app/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPartidasRoute =
  AuthenticatedAppPartidasRouteImport.update({
    id: '/app/partidas',
    path: '/app/partidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPrincipalRoute =
  AuthenticatedAppPrincipalRouteImport.update({
    id: '/app/principal',
    path: '/app/principal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRankingsRoute =
  AuthenticatedAppRankingsRouteImport.update({
    id: '/app/rankings',
    path: '/app/rankings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRodadasRoute = AuthenticatedAppRodadasRouteImport.update({
  id: '/app/rodadas',
  path: '/app/rodadas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSorteioRoute = AuthenticatedAppSorteioRouteImport.update({
  id: '/app/sorteio',
  path: '/app/sorteio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTorneiosRoute =
  AuthenticatedAppTorneiosRouteImport.update({
    id: '/app/torneios',
    path: '/app/torneios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/app/admin/',
    path: '/app/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminAuditoriaRoute =
  AuthenticatedAppAdminAuditoriaRouteImport.update({
    id: '/app/admin/auditoria',
    path: '/app/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminAvisosRoute =
  AuthenticatedAppAdminAvisosRouteImport.update({
    id: '/app/admin/avisos',
    path: '/app/admin/avisos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminConfiguracoesRoute =
  AuthenticatedAppAdminConfiguracoesRouteImport.update({
    id: '/app/admin/configuracoes',
    path: '/app/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminRelatoriosRoute =
  AuthenticatedAppAdminRelatoriosRouteImport.update({
    id: '/app/admin/relatorios',
    path: '/app/admin/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminRodadasRoute =
  AuthenticatedAppAdminRodadasRouteImport.update({
    id: '/app/admin/rodadas',
    path: '/app/admin/rodadas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminTemporadasRoute =
  AuthenticatedAppAdminTemporadasRouteImport.update({
    id: '/app/admin/temporadas',
    path: '/app/admin/temporadas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppJogadoresIdRoute =
  AuthenticatedAppJogadoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppJogadoresRoute,
  } as any)
const AuthenticatedAppPartidasIdRoute =
  AuthenticatedAppPartidasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppPartidasRoute,
  } as any)
const AuthenticatedAppRodadasIdRoute =
  AuthenticatedAppRodadasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppRodadasRoute,
  } as any)
const AuthenticatedAppTorneiosIdRoute =
  AuthenticatedAppTorneiosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppTorneiosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/jogadores': typeof AuthenticatedAppJogadoresRouteWithChildren
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/partidas': typeof AuthenticatedAppPartidasRouteWithChildren
  '/app/principal': typeof AuthenticatedAppPrincipalRoute
  '/app/rankings': typeof AuthenticatedAppRankingsRoute
  '/app/rodadas': typeof AuthenticatedAppRodadasRouteWithChildren
  '/app/sorteio': typeof AuthenticatedAppSorteioRoute
  '/app/torneios': typeof AuthenticatedAppTorneiosRouteWithChildren
  '/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/app/admin/avisos': typeof AuthenticatedAppAdminAvisosRoute
  '/app/admin/configuracoes': typeof AuthenticatedAppAdminConfiguracoesRoute
  '/app/admin/relatorios': typeof AuthenticatedAppAdminRelatoriosRoute
  '/app/admin/rodadas': typeof AuthenticatedAppAdminRodadasRoute
  '/app/admin/temporadas': typeof AuthenticatedAppAdminTemporadasRoute
  '/app/jogadores/$id': typeof AuthenticatedAppJogadoresIdRoute
  '/app/partidas/$id': typeof AuthenticatedAppPartidasIdRoute
  '/app/rodadas/$id': typeof AuthenticatedAppRodadasIdRoute
  '/app/torneios/$id': typeof AuthenticatedAppTorneiosIdRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/jogadores': typeof AuthenticatedAppJogadoresRouteWithChildren
  '/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/app/partidas': typeof AuthenticatedAppPartidasRouteWithChildren
  '/app/principal': typeof AuthenticatedAppPrincipalRoute
  '/app/rankings': typeof AuthenticatedAppRankingsRoute
  '/app/rodadas': typeof AuthenticatedAppRodadasRouteWithChildren
  '/app/sorteio': typeof AuthenticatedAppSorteioRoute
  '/app/torneios': typeof AuthenticatedAppTorneiosRouteWithChildren
  '/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/app/admin/avisos': typeof AuthenticatedAppAdminAvisosRoute
  '/app/admin/configuracoes': typeof AuthenticatedAppAdminConfiguracoesRoute
  '/app/admin/relatorios': typeof AuthenticatedAppAdminRelatoriosRoute
  '/app/admin/rodadas': typeof AuthenticatedAppAdminRodadasRoute
  '/app/admin/temporadas': typeof AuthenticatedAppAdminTemporadasRoute
  '/app/jogadores/$id': typeof AuthenticatedAppJogadoresIdRoute
  '/app/partidas/$id': typeof AuthenticatedAppPartidasIdRoute
  '/app/rodadas/$id': typeof AuthenticatedAppRodadasIdRoute
  '/app/torneios/$id': typeof AuthenticatedAppTorneiosIdRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/app/jogadores': typeof AuthenticatedAppJogadoresRouteWithChildren
  '/_authenticated/app/notificacoes': typeof AuthenticatedAppNotificacoesRoute
  '/_authenticated/app/partidas': typeof AuthenticatedAppPartidasRouteWithChildren
  '/_authenticated/app/principal': typeof AuthenticatedAppPrincipalRoute
  '/_authenticated/app/rankings': typeof AuthenticatedAppRankingsRoute
  '/_authenticated/app/rodadas': typeof AuthenticatedAppRodadasRouteWithChildren
  '/_authenticated/app/sorteio': typeof AuthenticatedAppSorteioRoute
  '/_authenticated/app/torneios': typeof AuthenticatedAppTorneiosRouteWithChildren
  '/_authenticated/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/_authenticated/app/admin/avisos': typeof AuthenticatedAppAdminAvisosRoute
  '/_authenticated/app/admin/configuracoes': typeof AuthenticatedAppAdminConfiguracoesRoute
  '/_authenticated/app/admin/relatorios': typeof AuthenticatedAppAdminRelatoriosRoute
  '/_authenticated/app/admin/rodadas': typeof AuthenticatedAppAdminRodadasRoute
  '/_authenticated/app/admin/temporadas': typeof AuthenticatedAppAdminTemporadasRoute
  '/_authenticated/app/jogadores/$id': typeof AuthenticatedAppJogadoresIdRoute
  '/_authenticated/app/partidas/$id': typeof AuthenticatedAppPartidasIdRoute
  '/_authenticated/app/rodadas/$id': typeof AuthenticatedAppRodadasIdRoute
  '/_authenticated/app/torneios/$id': typeof AuthenticatedAppTorneiosIdRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/recuperar-senha'
    | '/app/jogadores'
    | '/app/notificacoes'
    | '/app/partidas'
    | '/app/principal'
    | '/app/rankings'
    | '/app/rodadas'
    | '/app/sorteio'
    | '/app/torneios'
    | '/app/admin/auditoria'
    | '/app/admin/avisos'
    | '/app/admin/configuracoes'
    | '/app/admin/relatorios'
    | '/app/admin/rodadas'
    | '/app/admin/temporadas'
    | '/app/jogadores/$id'
    | '/app/partidas/$id'
    | '/app/rodadas/$id'
    | '/app/torneios/$id'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/recuperar-senha'
    | '/app/jogadores'
    | '/app/notificacoes'
    | '/app/partidas'
    | '/app/principal'
    | '/app/rankings'
    | '/app/rodadas'
    | '/app/sorteio'
    | '/app/torneios'
    | '/app/admin/auditoria'
    | '/app/admin/avisos'
    | '/app/admin/configuracoes'
    | '/app/admin/relatorios'
    | '/app/admin/rodadas'
    | '/app/admin/temporadas'
    | '/app/jogadores/$id'
    | '/app/partidas/$id'
    | '/app/rodadas/$id'
    | '/app/torneios/$id'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/primeiro-acesso'
    | '/recuperar-senha'
    | '/_authenticated/app/jogadores'
    | '/_authenticated/app/notificacoes'
    | '/_authenticated/app/partidas'
    | '/_authenticated/app/principal'
    | '/_authenticated/app/rankings'
    | '/_authenticated/app/rodadas'
    | '/_authenticated/app/sorteio'
    | '/_authenticated/app/torneios'
    | '/_authenticated/app/admin/auditoria'
    | '/_authenticated/app/admin/avisos'
    | '/_authenticated/app/admin/configuracoes'
    | '/_authenticated/app/admin/relatorios'
    | '/_authenticated/app/admin/rodadas'
    | '/_authenticated/app/admin/temporadas'
    | '/_authenticated/app/jogadores/$id'
    | '/_authenticated/app/partidas/$id'
    | '/_authenticated/app/rodadas/$id'
    | '/_authenticated/app/torneios/$id'
    | '/_authenticated/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/jogadores': {
      id: '/_authenticated/app/jogadores'
      path: '/app/jogadores'
      fullPath: '/app/jogadores'
      preLoaderRoute: typeof AuthenticatedAppJogadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/notificacoes': {
      id: '/_authenticated/app/notificacoes'
      path: '/app/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AuthenticatedAppNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/partidas': {
      id: '/_authenticated/app/partidas'
      path: '/app/partidas'
      fullPath: '/app/partidas'
      preLoaderRoute: typeof AuthenticatedAppPartidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/principal': {
      id: '/_authenticated/app/principal'
      path: '/app/principal'
      fullPath: '/app/principal'
      preLoaderRoute: typeof AuthenticatedAppPrincipalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/rankings': {
      id: '/_authenticated/app/rankings'
      path: '/app/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AuthenticatedAppRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/rodadas': {
      id: '/_authenticated/app/rodadas'
      path: '/app/rodadas'
      fullPath: '/app/rodadas'
      preLoaderRoute: typeof AuthenticatedAppRodadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sorteio': {
      id: '/_authenticated/app/sorteio'
      path: '/app/sorteio'
      fullPath: '/app/sorteio'
      preLoaderRoute: typeof AuthenticatedAppSorteioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/torneios': {
      id: '/_authenticated/app/torneios'
      path: '/app/torneios'
      fullPath: '/app/torneios'
      preLoaderRoute: typeof AuthenticatedAppTorneiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/app/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/auditoria': {
      id: '/_authenticated/app/admin/auditoria'
      path: '/app/admin/auditoria'
      fullPath: '/app/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/avisos': {
      id: '/_authenticated/app/admin/avisos'
      path: '/app/admin/avisos'
      fullPath: '/app/admin/avisos'
      preLoaderRoute: typeof AuthenticatedAppAdminAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/configuracoes': {
      id: '/_authenticated/app/admin/configuracoes'
      path: '/app/admin/configuracoes'
      fullPath: '/app/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/relatorios': {
      id: '/_authenticated/app/admin/relatorios'
      path: '/app/admin/relatorios'
      fullPath: '/app/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAppAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/rodadas': {
      id: '/_authenticated/app/admin/rodadas'
      path: '/app/admin/rodadas'
      fullPath: '/app/admin/rodadas'
      preLoaderRoute: typeof AuthenticatedAppAdminRodadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/temporadas': {
      id: '/_authenticated/app/admin/temporadas'
      path: '/app/admin/temporadas'
      fullPath: '/app/admin/temporadas'
      preLoaderRoute: typeof AuthenticatedAppAdminTemporadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/jogadores/$id': {
      id: '/_authenticated/app/jogadores/$id'
      path: '/$id'
      fullPath: '/app/jogadores/$id'
      preLoaderRoute: typeof AuthenticatedAppJogadoresIdRouteImport
      parentRoute: typeof AuthenticatedAppJogadoresRoute
    }
    '/_authenticated/app/partidas/$id': {
      id: '/_authenticated/app/partidas/$id'
      path: '/$id'
      fullPath: '/app/partidas/$id'
      preLoaderRoute: typeof AuthenticatedAppPartidasIdRouteImport
      parentRoute: typeof AuthenticatedAppPartidasRoute
    }
    '/_authenticated/app/rodadas/$id': {
      id: '/_authenticated/app/rodadas/$id'
      path: '/$id'
      fullPath: '/app/rodadas/$id'
      preLoaderRoute: typeof AuthenticatedAppRodadasIdRouteImport
      parentRoute: typeof AuthenticatedAppRodadasRoute
    }
    '/_authenticated/app/torneios/$id': {
      id: '/_authenticated/app/torneios/$id'
      path: '/$id'
      fullPath: '/app/torneios/$id'
      preLoaderRoute: typeof AuthenticatedAppTorneiosIdRouteImport
      parentRoute: typeof AuthenticatedAppTorneiosRoute
    }
  }
}

interface AuthenticatedAppJogadoresRouteChildren {
  AuthenticatedAppJogadoresIdRoute: typeof AuthenticatedAppJogadoresIdRoute
}

const AuthenticatedAppJogadoresRouteChildren: AuthenticatedAppJogadoresRouteChildren =
  {
    AuthenticatedAppJogadoresIdRoute: AuthenticatedAppJogadoresIdRoute,
  }

const AuthenticatedAppJogadoresRouteWithChildren =
  AuthenticatedAppJogadoresRoute._addFileChildren(
    AuthenticatedAppJogadoresRouteChildren,
  )

interface AuthenticatedAppPartidasRouteChildren {
  AuthenticatedAppPartidasIdRoute: typeof AuthenticatedAppPartidasIdRoute
}

const AuthenticatedAppPartidasRouteChildren: AuthenticatedAppPartidasRouteChildren =
  {
    AuthenticatedAppPartidasIdRoute: AuthenticatedAppPartidasIdRoute,
  }

const AuthenticatedAppPartidasRouteWithChildren =
  AuthenticatedAppPartidasRoute._addFileChildren(
    AuthenticatedAppPartidasRouteChildren,
  )

interface AuthenticatedAppRodadasRouteChildren {
  AuthenticatedAppRodadasIdRoute: typeof AuthenticatedAppRodadasIdRoute
}

const AuthenticatedAppRodadasRouteChildren: AuthenticatedAppRodadasRouteChildren =
  {
    AuthenticatedAppRodadasIdRoute: AuthenticatedAppRodadasIdRoute,
  }

const AuthenticatedAppRodadasRouteWithChildren =
  AuthenticatedAppRodadasRoute._addFileChildren(
    AuthenticatedAppRodadasRouteChildren,
  )

interface AuthenticatedAppTorneiosRouteChildren {
  AuthenticatedAppTorneiosIdRoute: typeof AuthenticatedAppTorneiosIdRoute
}

const AuthenticatedAppTorneiosRouteChildren: AuthenticatedAppTorneiosRouteChildren =
  {
    AuthenticatedAppTorneiosIdRoute: AuthenticatedAppTorneiosIdRoute,
  }

const AuthenticatedAppTorneiosRouteWithChildren =
  AuthenticatedAppTorneiosRoute._addFileChildren(
    AuthenticatedAppTorneiosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppJogadoresRoute: typeof AuthenticatedAppJogadoresRouteWithChildren
  AuthenticatedAppNotificacoesRoute: typeof AuthenticatedAppNotificacoesRoute
  AuthenticatedAppPartidasRoute: typeof AuthenticatedAppPartidasRouteWithChildren
  AuthenticatedAppPrincipalRoute: typeof AuthenticatedAppPrincipalRoute
  AuthenticatedAppRankingsRoute: typeof AuthenticatedAppRankingsRoute
  AuthenticatedAppRodadasRoute: typeof AuthenticatedAppRodadasRouteWithChildren
  AuthenticatedAppSorteioRoute: typeof AuthenticatedAppSorteioRoute
  AuthenticatedAppTorneiosRoute: typeof AuthenticatedAppTorneiosRouteWithChildren
  AuthenticatedAppAdminAuditoriaRoute: typeof AuthenticatedAppAdminAuditoriaRoute
  AuthenticatedAppAdminAvisosRoute: typeof AuthenticatedAppAdminAvisosRoute
  AuthenticatedAppAdminConfiguracoesRoute: typeof AuthenticatedAppAdminConfiguracoesRoute
  AuthenticatedAppAdminRelatoriosRoute: typeof AuthenticatedAppAdminRelatoriosRoute
  AuthenticatedAppAdminRodadasRoute: typeof AuthenticatedAppAdminRodadasRoute
  AuthenticatedAppAdminTemporadasRoute: typeof AuthenticatedAppAdminTemporadasRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppJogadoresRoute: AuthenticatedAppJogadoresRouteWithChildren,
  AuthenticatedAppNotificacoesRoute: AuthenticatedAppNotificacoesRoute,
  AuthenticatedAppPartidasRoute: AuthenticatedAppPartidasRouteWithChildren,
  AuthenticatedAppPrincipalRoute: AuthenticatedAppPrincipalRoute,
  AuthenticatedAppRankingsRoute: AuthenticatedAppRankingsRoute,
  AuthenticatedAppRodadasRoute: AuthenticatedAppRodadasRouteWithChildren,
  AuthenticatedAppSorteioRoute: AuthenticatedAppSorteioRoute,
  AuthenticatedAppTorneiosRoute: AuthenticatedAppTorneiosRouteWithChildren,
  AuthenticatedAppAdminAuditoriaRoute: AuthenticatedAppAdminAuditoriaRoute,
  AuthenticatedAppAdminAvisosRoute: AuthenticatedAppAdminAvisosRoute,
  AuthenticatedAppAdminConfiguracoesRoute:
    AuthenticatedAppAdminConfiguracoesRoute,
  AuthenticatedAppAdminRelatoriosRoute: AuthenticatedAppAdminRelatoriosRoute,
  AuthenticatedAppAdminRodadasRoute: AuthenticatedAppAdminRodadasRoute,
  AuthenticatedAppAdminTemporadasRoute: AuthenticatedAppAdminTemporadasRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
