/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedAppJogadoresRouteImport } from './routes/_authenticated/app/jogadores'
import { Route as AuthenticatedAppPrincipalRouteImport } from './routes/_authenticated/app/principal'
import { Route as AuthenticatedAppRodadasRouteImport } from './routes/_authenticated/app/rodadas'
import { Route as AuthenticatedAppSorteioRouteImport } from './routes/_authenticated/app/sorteio'
import { Route as AuthenticatedAppTorneiosRouteImport } from './routes/_authenticated/app/torneios'
import { Route as AuthenticatedAppAdminRodadasRouteImport } from './routes/_authenticated/app/admin/rodadas'
import { Route as AuthenticatedAppAdminTemporadasRouteImport } from './routes/_authenticated/app/admin/temporadas'
import { Route as AuthenticatedAppJogadoresIdRouteImport } from './routes/_authenticated/app/jogadores.$id'
import { Route as AuthenticatedAppRodadasIdRouteImport } from './routes/_authenticated/app/rodadas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppJogadoresRoute =
  AuthenticatedAppJogadoresRouteImport.update({
    id: '/app/jogadores',
    path: '/app/jogadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPrincipalRoute =
  AuthenticatedAppPrincipalRouteImport.update({
    id: '/app/principal',
    path: '/app/principal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRodadasRoute = AuthenticatedAppRodadasRouteImport.update({
  id: '/app/rodadas',
  path: '/app/rodadas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSorteioRoute = AuthenticatedAppSorteioRouteImport.update({
  id: '/app/sorteio',
  path: '/app/sorteio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTorneiosRoute =
  AuthenticatedAppTorneiosRouteImport.update({
    id: '/app/torneios',
    path: '/app/torneios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminRodadasRoute =
  AuthenticatedAppAdminRodadasRouteImport.update({
    id: '/rodadas',
    path: '/rodadas',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminTemporadasRoute =
  AuthenticatedAppAdminTemporadasRouteImport.update({
    id: '/temporadas',
    path: '/temporadas',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppJogadoresIdRoute =
  AuthenticatedAppJogadoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppJogadoresRoute,
  } as any)
const AuthenticatedAppRodadasIdRoute =
  AuthenticatedAppRodadasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppRodadasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/jogadores': typeof AuthenticatedAppJogadoresRouteWithChildren
  '/app/principal': typeof AuthenticatedAppPrincipalRoute
  '/app/rodadas': typeof AuthenticatedAppRodadasRouteWithChildren
  '/app/sorteio': typeof AuthenticatedAppSorteioRoute
  '/app/torneios': typeof AuthenticatedAppTorneiosRoute
  '/app/admin/rodadas': typeof AuthenticatedAppAdminRodadasRoute
  '/app/admin/temporadas': typeof AuthenticatedAppAdminTemporadasRoute
  '/app/jogadores/$id': typeof AuthenticatedAppJogadoresIdRoute
  '/app/rodadas/$id': typeof AuthenticatedAppRodadasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/jogadores': typeof AuthenticatedAppJogadoresRouteWithChildren
  '/app/principal': typeof AuthenticatedAppPrincipalRoute
  '/app/rodadas': typeof AuthenticatedAppRodadasRouteWithChildren
  '/app/sorteio': typeof AuthenticatedAppSorteioRoute
  '/app/torneios': typeof AuthenticatedAppTorneiosRoute
  '/app/admin/rodadas': typeof AuthenticatedAppAdminRodadasRoute
  '/app/admin/temporadas': typeof AuthenticatedAppAdminTemporadasRoute
  '/app/jogadores/$id': typeof AuthenticatedAppJogadoresIdRoute
  '/app/rodadas/$id': typeof AuthenticatedAppRodadasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/jogadores': typeof AuthenticatedAppJogadoresRouteWithChildren
  '/_authenticated/app/principal': typeof AuthenticatedAppPrincipalRoute
  '/_authenticated/app/rodadas': typeof AuthenticatedAppRodadasRouteWithChildren
  '/_authenticated/app/sorteio': typeof AuthenticatedAppSorteioRoute
  '/_authenticated/app/torneios': typeof AuthenticatedAppTorneiosRoute
  '/_authenticated/app/admin/rodadas': typeof AuthenticatedAppAdminRodadasRoute
  '/_authenticated/app/admin/temporadas': typeof AuthenticatedAppAdminTemporadasRoute
  '/_authenticated/app/jogadores/$id': typeof AuthenticatedAppJogadoresIdRoute
  '/_authenticated/app/rodadas/$id': typeof AuthenticatedAppRodadasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/recuperar-senha'
    | '/app/admin'
    | '/app/jogadores'
    | '/app/principal'
    | '/app/rodadas'
    | '/app/sorteio'
    | '/app/torneios'
    | '/app/admin/rodadas'
    | '/app/admin/temporadas'
    | '/app/jogadores/$id'
    | '/app/rodadas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/primeiro-acesso'
    | '/recuperar-senha'
    | '/app/admin'
    | '/app/jogadores'
    | '/app/principal'
    | '/app/rodadas'
    | '/app/sorteio'
    | '/app/torneios'
    | '/app/admin/rodadas'
    | '/app/admin/temporadas'
    | '/app/jogadores/$id'
    | '/app/rodadas/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/primeiro-acesso'
    | '/recuperar-senha'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/jogadores'
    | '/_authenticated/app/principal'
    | '/_authenticated/app/rodadas'
    | '/_authenticated/app/sorteio'
    | '/_authenticated/app/torneios'
    | '/_authenticated/app/admin/rodadas'
    | '/_authenticated/app/admin/temporadas'
    | '/_authenticated/app/jogadores/$id'
    | '/_authenticated/app/rodadas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/jogadores': {
      id: '/_authenticated/app/jogadores'
      path: '/app/jogadores'
      fullPath: '/app/jogadores'
      preLoaderRoute: typeof AuthenticatedAppJogadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/principal': {
      id: '/_authenticated/app/principal'
      path: '/app/principal'
      fullPath: '/app/principal'
      preLoaderRoute: typeof AuthenticatedAppPrincipalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/rodadas': {
      id: '/_authenticated/app/rodadas'
      path: '/app/rodadas'
      fullPath: '/app/rodadas'
      preLoaderRoute: typeof AuthenticatedAppRodadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sorteio': {
      id: '/_authenticated/app/sorteio'
      path: '/app/sorteio'
      fullPath: '/app/sorteio'
      preLoaderRoute: typeof AuthenticatedAppSorteioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/torneios': {
      id: '/_authenticated/app/torneios'
      path: '/app/torneios'
      fullPath: '/app/torneios'
      preLoaderRoute: typeof AuthenticatedAppTorneiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/rodadas': {
      id: '/_authenticated/app/admin/rodadas'
      path: '/rodadas'
      fullPath: '/app/admin/rodadas'
      preLoaderRoute: typeof AuthenticatedAppAdminRodadasRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/temporadas': {
      id: '/_authenticated/app/admin/temporadas'
      path: '/temporadas'
      fullPath: '/app/admin/temporadas'
      preLoaderRoute: typeof AuthenticatedAppAdminTemporadasRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/jogadores/$id': {
      id: '/_authenticated/app/jogadores/$id'
      path: '/$id'
      fullPath: '/app/jogadores/$id'
      preLoaderRoute: typeof AuthenticatedAppJogadoresIdRouteImport
      parentRoute: typeof AuthenticatedAppJogadoresRoute
    }
    '/_authenticated/app/rodadas/$id': {
      id: '/_authenticated/app/rodadas/$id'
      path: '/$id'
      fullPath: '/app/rodadas/$id'
      preLoaderRoute: typeof AuthenticatedAppRodadasIdRouteImport
      parentRoute: typeof AuthenticatedAppRodadasRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminRodadasRoute: typeof AuthenticatedAppAdminRodadasRoute
  AuthenticatedAppAdminTemporadasRoute: typeof AuthenticatedAppAdminTemporadasRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminRodadasRoute: AuthenticatedAppAdminRodadasRoute,
  AuthenticatedAppAdminTemporadasRoute: AuthenticatedAppAdminTemporadasRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppJogadoresRouteChildren {
  AuthenticatedAppJogadoresIdRoute: typeof AuthenticatedAppJogadoresIdRoute
}

const AuthenticatedAppJogadoresRouteChildren: AuthenticatedAppJogadoresRouteChildren =
  {
    AuthenticatedAppJogadoresIdRoute: AuthenticatedAppJogadoresIdRoute,
  }

const AuthenticatedAppJogadoresRouteWithChildren =
  AuthenticatedAppJogadoresRoute._addFileChildren(
    AuthenticatedAppJogadoresRouteChildren,
  )

interface AuthenticatedAppRodadasRouteChildren {
  AuthenticatedAppRodadasIdRoute: typeof AuthenticatedAppRodadasIdRoute
}

const AuthenticatedAppRodadasRouteChildren: AuthenticatedAppRodadasRouteChildren =
  {
    AuthenticatedAppRodadasIdRoute: AuthenticatedAppRodadasIdRoute,
  }

const AuthenticatedAppRodadasRouteWithChildren =
  AuthenticatedAppRodadasRoute._addFileChildren(
    AuthenticatedAppRodadasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppJogadoresRoute: typeof AuthenticatedAppJogadoresRouteWithChildren
  AuthenticatedAppPrincipalRoute: typeof AuthenticatedAppPrincipalRoute
  AuthenticatedAppRodadasRoute: typeof AuthenticatedAppRodadasRouteWithChildren
  AuthenticatedAppSorteioRoute: typeof AuthenticatedAppSorteioRoute
  AuthenticatedAppTorneiosRoute: typeof AuthenticatedAppTorneiosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppJogadoresRoute: AuthenticatedAppJogadoresRouteWithChildren,
  AuthenticatedAppPrincipalRoute: AuthenticatedAppPrincipalRoute,
  AuthenticatedAppRodadasRoute: AuthenticatedAppRodadasRouteWithChildren,
  AuthenticatedAppSorteioRoute: AuthenticatedAppSorteioRoute,
  AuthenticatedAppTorneiosRoute: AuthenticatedAppTorneiosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
